# -*- coding: utf-8 -*-
"""N-body Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ha0n0a_4KnV_TjIoC1yrq3o4tefN7HPS
"""

import numpy as np
import matplotlib.pyplot as plt

class particle:
  def __init__(self, mass, x_0, y_0, vx_0, vy_0):
    self.mass = mass
    self.X = [x_0]
    self.Y = [y_0]
    self.Vx = [vx_0]
    self.Vy = [vy_0]
    self.E = []

G = 1
err = 1e-12

def gravity(p1, p2):

  if p1 is not p2:

    delta_x_21 = p2.X[-1] - p1.X[-1]
    delta_y_21 = p2.Y[-1] - p1.Y[-1]

    r = np.sqrt(delta_x_21**2 + delta_y_21**2 + err**2)

    F = G * p1.mass * p2.mass / r**2

    Fx = F * delta_x_21 / r
    Fy = F * delta_y_21 / r

    return np.array([Fx, Fy])

  else:
    return np.array([0, 0])

# Determine N
while True:
    try:
        N = int(input("Enter Number of Particles: "))
        if N > 0:
            break
        else:
            print("Number of particles must be greater than 0.")
    except ValueError:
        print("Please enter a valid integer.")


particles = []

for i in range(N):
    print(f"\nParticle {i+1}")
    while True:
        try:
            mass = float(input("Enter Mass: "))
            if mass > 0:
                break
            else:
                print("Mass must be positive.")

        except ValueError:
            print("Please enter a valid number.")
    while True:
        try:
            x_0 = float(input("Enter Initial X-Coordinate: "))
            y_0 = float(input("Enter Initial Y-Coordinate: "))
            vx_0 = float(input("Enter Initial X-Velocity: "))
            vy_0 = float(input("Enter Initial Y-Velocity: "))
            break

        except ValueError:
            print("Please enter valid numerical values.")

    particles.append(
        particle(mass, x_0, y_0, vx_0, vy_0)
    )

"""Now that we have determined the number of particles $N$, we can determine the net force on each particle."""

def Force(particles):
  Forces = np.array([
    np.sum(
        [gravity(particles[i], particles[u]) for u in range(N) if u != i],
        axis=0
    )
    for i in range(N)
  ])

  return Forces

while True:
  delta_t = float(input("Enter the time step: "))
  if delta_t>0:
    delta_t = float(delta_t)
    T = float(input("Enter the total time: "))
    if T>0:
      T = float(T)
      break
    else:
      print("Enter a valid input as time!")
  else:
    print("Enter a valid input as time step!")

for t in range(int(T/delta_t)):
  Forces = Force(particles)
  for i in range(N):
    if t >= 1:
      x = 2*particles[i].X[-1] - particles[i].X[-2] + Forces[i][0]*(delta_t**2)/particles[i].mass
      y = 2*particles[i].Y[-1] - particles[i].Y[-2] + Forces[i][1]*(delta_t**2)/particles[i].mass
      particles[i].X.append(x)
      particles[i].Y.append(y)
    else:
      x = particles[i].X[-1] + particles[i].Vx[-1]*delta_t + 0.5*Forces[i][0]*(delta_t**2)/particles[i].mass
      y = particles[i].Y[-1] + particles[i].Vy[-1]*delta_t + 0.5*Forces[i][1]*(delta_t**2)/particles[i].mass
      particles[i].X.append(x)
      particles[i].Y.append(y)

R_x = []
R_y = []

for t in range(len(particles[0].X)):

    total_mass = sum(p.mass for p in particles)

    x_cm = sum(
        p.mass * p.X[t]
        for p in particles
    ) / total_mass

    y_cm = sum(
        p.mass * p.Y[t]
        for p in particles
    ) / total_mass

    R_x.append(x_cm)
    R_y.append(y_cm)

for i, p in enumerate(particles):
    plt.plot(p.X, p.Y, label=f"Particle {i+1}")
plt.plot(R_x, R_y, label = "Center of Mass of system")

plt.legend()
plt.axis("equal")
plt.grid()
plt.show()

"""ENERGY PLOTS

"""

for t in range(1, int(T/delta_t)):
  for p in particles:
    p.Vx.append((p.X[t]-p.X[t-1])/delta_t)
    p.Vy.append((p.Y[t]-p.Y[t-1])/delta_t)

for t in range(int(T/delta_t)):
  for p in particles:
    K = (1/2)*p.mass*(p.Vx[t]**2+p.Vy[t]**2)
    U = -sum(G*p.mass*p1.mass/np.sqrt((p1.X[t]-p.X[t])**2+(p1.Y[t]-p.Y[t])**2+err**2)
            for p1 in particles if p is not p1)
    p.E.append(K+U)

Total_Energy = []
Kinetic_Energy = []
for t in range(int(T/delta_t)):
  for p in particles:
    Kinetic_Energy.append((1/2)*p.mass*(p.Vx[t]**2+p.Vy[t]**2))
  Total_Energy.append(sum(Kinetic_Energy))
  Kinetic_Energy = []

Potential_Energy = []

for t in range(int(T/delta_t)):
    Potential_Energy.append(-sum(G*p1.mass*p2.mass/np.sqrt((p1.X[t]-p2.X[t])**2+(p1.Y[t]-p2.Y[t])**2+err**2)
                            for p1 in particles for p2 in particles if p1 is not p2))

Total_Energy = np.array(Total_Energy)
Potential_Energy = np.array(Potential_Energy)/2
Total_Energy += Potential_Energy

Time = np.arange(0, int(T/delta_t))
for p in particles:
    plt.plot(Time*delta_t, p.E, label=f"Particle {particles.index(p)+1}")

plt.xlabel("Time")
plt.ylabel("Energy")
plt.legend()
plt.show()

plt.plot(Time*delta_t, Total_Energy, label = "Total Energy")
plt.xlabel("Time")
plt.ylabel("Energy")
plt.legend()
plt.show()

"""ANIMATION : VISUAL SIMULATION"""

from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots(facecolor = 'black')

ax.set_facecolor('black')

colors = ['gold', 'cyan', 'white', 'red', 'orange', 'blue']

X_max, X_min, Y_max, Y_min = 0, 0, 0, 0
for p in particles:
  x_max = max(p.X)
  x_min = min(p.X)
  y_max = max(p.Y)
  y_min = min(p.Y)
  X_max = max(x_max, X_max)
  X_min = min(x_min, X_min)
  Y_max = max(y_max, Y_max)
  Y_min = min(y_min, Y_min)

ax.set_xlim(X_min-1, X_max+1)
ax.set_ylim(Y_min-1, Y_max+1)

ax.set_aspect('equal')

points = [
    ax.plot([], [], 'o', color = colors[i], label=f"Particle {i+1}\n Mass = {particles[i].mass}")[0]
    for i in range(N)
]

trails = [
    ax.plot([], [], lw=1, color = colors[i])[0]
    for i in range(N)
]

def init():

    for point, trail in zip(points, trails):

        point.set_data([], [])
        trail.set_data([], [])

    return points + trails


def update_frame(frame):

    for i, p in enumerate(particles):

        x = p.X[frame]
        y = p.Y[frame]

        points[i].set_data([x], [y])

        trails[i].set_data(
            p.X[:frame],
            p.Y[:frame]
        )

    return points + trails


anim = FuncAnimation(
    fig,
    update_frame,
    frames=range(0, len(particles[0].X), 100),
    init_func=init,
    interval=20,
    blit=True
)

plt.legend()


from IPython.display import HTML

HTML(anim.to_jshtml())

#anim.save("n_body_simulation.mp4", writer="ffmpeg", fps=30)

#from google.colab import files
#files.download("n_body_simulation.mp4")

#Use this code to download the video of the animation!
#Thank You!